ALTER TABLE users
    ADD COLUMN name VARCHAR(100) NULL,
    ADD COLUMN gender VARCHAR(10) NULL,
    ADD COLUMN joined_date DATE DEFAULT CURRENT_DATE,
    ADD COLUMN description VARCHAR(1000) NULL,
    ADD COLUMN avatar VARCHAR(500) NULL,
    ADD COLUMN background VARCHAR(500) NULL;
