DROP TABLE IF EXISTS replenishment_event CASCADE;
DROP TABLE IF EXISTS shelf_alert CASCADE;
DROP TABLE IF EXISTS osa_measurement CASCADE;
DROP TABLE IF EXISTS shelf_operation CASCADE;
DROP TABLE IF EXISTS customer_visit CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS shelf CASCADE;
